name: Deploy Laravel para EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar SSH e copiar arquivos para o EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Copiar arquivos para o servidor
        rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./ $EC2_USER@$EC2_HOST:$DEPLOY_DIR

    - name: Rodar comandos de deploy no EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          cd $DEPLOY_DIR
          git pull origin main
          composer install --no-dev --prefer-dist
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          chmod -R 775 storage bootstrap/cache
          sudo systemctl restart nginx
          sudo systemctl restart php8.3-fpm  # Ajuste conforme sua versão do PHP
        EOF
